# https://taskfile.dev
version: '3'
vars:
  BINFILE: ansible-summary

tasks:
  default:
    desc: "List all tasks"
    cmds:
      - task -a

  build:
    desc: "Build the binary"
    cmds:
      - go mod download
      - task: sqlc
      - CGO_ENABLED=0 go build .

  linter:
    desc: "Run linter"
    cmds:
      - go generate ./...
      - golangci-lint run

  snapshot:
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean --snapshot
    
  release:
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean